spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/forohub_api

spring.datasource.username=root

spring.datasource.password=eliana12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.secret=12345678
logging.level.org.springframework.security=TRACE
src/main/resources/application.properties